create
or replace TABLE CUSTOMERS (
    CUSTOMERSK NUMBER(38, 0) NOT NULL autoincrement,
    CUSTOMERID VARCHAR(5) NOT NULL,
    COMPANYNAME VARCHAR(40) NOT NULL,
    CONTACTNAME VARCHAR(30),
    CONTACTTITLE VARCHAR(30),
    ADDRESS VARCHAR(60),
    CITY VARCHAR(15),
    REGION VARCHAR(15),
    POSTALCODE VARCHAR(10),
    COUNTRY VARCHAR(15),
    CRECORDSTARTDATE DATE DEFAULT CURRENT_DATE(),
    primary key (CUSTOMERSK)
);
create
or replace TABLE EMPLOYEES (
    EMPLOYEESK NUMBER(38, 0) NOT NULL autoincrement,
    EMPLOYEEID NUMBER(38, 0) NOT NULL,
    LASTNAME VARCHAR(20) NOT NULL,
    FIRSTNAME VARCHAR(10) NOT NULL,
    TITLE VARCHAR(30),
    TITLEOFCOURTESY VARCHAR(25),
    BIRTHDATE DATE,
    HIREDATE DATE,
    ADDRESS VARCHAR(60),
    CITY VARCHAR(15),
    REGION VARCHAR(15),
    POSTALCODE VARCHAR(10),
    COUNTRY VARCHAR(15),
    NOTES VARCHAR(16777216),
    REPORTSTO NUMBER(38, 0),
    ERECORDSTARTDATE DATE DEFAULT CURRENT_DATE(),
    primary key (EMPLOYEESK)
);
create
or replace TABLE SUPPLIERS (
    SUPPLIERSK NUMBER(38, 0) NOT NULL autoincrement,
    SUPPLIERID NUMBER(38, 0) NOT NULL,
    COMPANYNAME VARCHAR(40) NOT NULL,
    CONTACTNAME VARCHAR(30),
    CONTACTTITLE VARCHAR(30),
    ADDRESS VARCHAR(60),
    CITY VARCHAR(15),
    REGION VARCHAR(15),
    POSTALCODE VARCHAR(10),
    COUNTRY VARCHAR(15),
    SRECORDSTARTDATE DATE DEFAULT CURRENT_DATE(),
    primary key (SUPPLIERSK)
);